# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be0504a4d3084b7040e1af8528556c3ab6c04d99d1ae5dc3190738f67a2c4a153533047648a196fb237e338df014cfc0adfe578598a70d22071a7a6c0f99a78d

test:
  secret_key_base: fd0338ecf23cf7356da8444b42442bd4ae3471ba4ff9487d33588d0a7eede53c2f7788aa05d1876541555a9dd7b333672eb2b3df25a0c52001503b86aae78bde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
